const DASHBOARD_DATA_SET = 'DASHBOARD_DATA_SET';
const UPDATED_EMPLOYEE_DATA = 'UPDATED_EMPLOYEE_DATA';
const CLEAR_UPDATED_EMPLOYEE_DATA = 'CLEAR_UPDATED_EMPLOYEE_DATA';
const SAVE_EMPLOYEES_DATA = 'SAVE_EMPLOYEES_DATA';

export {
    DASHBOARD_DATA_SET,
    UPDATED_EMPLOYEE_DATA,
    CLEAR_UPDATED_EMPLOYEE_DATA,
    SAVE_EMPLOYEES_DATA
}